minVersion: 0.23.1
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: registry
    sdks:
      npm:@sentry-internal/node-cpu-profiler:
  - name: github
